### ISSUE TITLE
no ini update

### ISSUE THREAD

**Issue by bumpouz** [ITotalJustice/tinfoil-updater#3]
Hey , great work on all your updaters. Would it be possible to add an option to not update the ini files in atmosphere like your atmo/hekate updater? When tinfoil updates it overwrites it and have to manually go in and set the cheats to not run and it changes the hekate reboot to payload. I can just rerun the atmosphere updater to fix the hekate reboot to payload problem but at that point the ini still has to be changed.
Thanks for the hardwork

**Comment by ITotalJustice** [comment]
Hi!
I am surprised that people still use this updater, especially now as Tinfoil _finally_ has a built in updater now. 😄 

I will add this option at some point, for now I'd recommend using the `tinfoil folder update` as it will only update the contents of the tinfoil folder, so it won't mess with your cfw setup.

Thank you for using my app!
